apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlimachip-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rlimachip-flask-app
  template:
    metadata:
      labels:
        app: rlimachip-flask-app
    spec:
      containers:
        - name: flask-app
          image: rlimachip/rlimachip-docker-demo:rlimachip-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: rlimachip-flask-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: rlimachip-flask-app

